apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: bobo
  labels:
    l1: DevOps
spec:
  selector:
    matchLabels:
      app: new
  template:
    metadata:
      labels:
        app: new
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: bobo-service
spec:
  selector:
    app: new
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
