apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
  labels:
    app: apache
  annotations:
    kubernetes.io/change-cause: "Version 1"
spec:
  replicas: 6
  minReadySeconds: 20
  strategy:
    type: Recreate
    
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
        - name: apache
          image:  docker9447/apache:v1
          ports:
            - containerPort: 80
