apiVersion: v1
kind: Pod
metadata: 
  name: pod1
  labels:
    label1: aws
    label2: docker
    label3: linux
spec:
  containers:
    - name: firstcontainer
      image: nginx:1.23

---
apiVersion: v1
kind: Pod
metadata: 
  name: pod2
  labels:
    label1: aws
    label2: docker
    label3: linux
spec:
  containers:
    - name: secondcontainer
      image: nginx:1.23
      env:
      - name: myname
        value: Khan
      - name: city 
        value: Chishtian
