apiVersion: v1
kind: Pod 
metadata: 
  name: nginx-webserver
spec:
  containers:
    - image: nginx
      name: webserver
      imagePullPolicy: IfNotPresent
      ports:
      - containerPort: 80
        name: http
      volumeMounts:
      - mountPath: /usr/share/nginx/html
        name: app-data
  volumes:
  - name: app-data
    persistentVolumeClaim:
      claimName: my-pvc-hostpath