apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv-hostpath
spec:
  capacity:
    storage: 1Gi
  accessModes: 
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostpath: 
    path: /data/my-pv-hostpath
   
  