apiVersion: v1
kind: PersistentVolumeClaim 
metadata:
  name: my-pvc-hostpath
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
  volumeName: my-pv-hostpath   
  