apiVersion: v1
kind: Pod
metadata:
  name: my-pod-emptydir
spec:
  containers:
    - name: my-pod-emptydir
      image: nginx
      imagePullPolicy: IfNotPresent
      VolumeMounts:
        - name: emptydir-vol
          mountpath: /usr/share/nginx/html
  volumes:
    - name: emptydir-vol
      emptyDir:
        sizeLimit: 500Mi