apiVersion: v1
kind: Pod
metadata:
  name: my-taint-pod
spec: 
  containers:
  - name: my-container
    image: nginx
  tolerations:
  - key: name
    operator: "Equal"
    value: bobo
    effect: "NoSchedule"
