apiVersion: v1
kind: Pod
metadata:
  name: my-taint-pod
  spec: 
    containers:
    - name: my-container
      image: nginx
    tolerations:
    - key: key1
      operator: "Equal"
      value: value1
      effect: "NoSchedule"